jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.3

      - name: Start MongoDB container
        run: |
          docker run -d --name mongodb -p 27017:27017 mongo:8.0.11
          # Wait for MongoDB to be ready
          for i in {1..30}; do
            if mongo --eval "db.adminCommand('ping')" &>/dev/null; then
              echo "MongoDB is ready"
              break
            fi
            echo "Waiting for MongoDB to start..."
            sleep 2
          done

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          MONGODB_URI: mongodb://localhost:27017/kontratat
          CI: true
        run: npm test
